#!/bin/bash

node ./scripts/release.js

if [ -z "$(git status --porcelain)" ]; then
	# Bump package.json with patch, minor, or major
	npm version $1 --git-tag-version=false

	cd "$(dirname "$0")/.."

	# Get the current version
	version=$(./scripts/version)

	echo Packaging version $version

	zipfile=releases/tupiq-$version.zip

	files="bin"

	zip -FSr -X $zipfile $files -x \*bower.json \*.bowerrc

	echo Packaged $zipfile

	git add .

	git commit -m "Version $version"

	git tag -a v$version -m "Version $version"
else
	echo Working directory is not clean. Commit or stash and try again.
fi
