#!/usr/bin/env node

var release = process.argv[2];

if (release !== 'patch' && release !== 'minor' && release !== 'major') {
	console.log('Invalid release type. Please supply either patch, minor, or major.');
	return;
}

var npm = require('npm');

npm.load(function (err, npm) {
    npm.commands.version([release], function (err) {
        if (err) {
        	console.log(err);
        } else {

        }
    });
});
