#!/usr/bin/env node

var npm = require('npm');

npm.load(function (err, npm) {
    npm.commands.version(['patch'], function (err) {
        if (err) {
        	console.log(err);
        }

        console.log(arguments);
    });
});
